version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - mynetwork


  database:
    image: postgres:alpine
    container_name: my-database
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Map the PostgreSQL port to the host machine
    environment:
     - DATABASE_HOST="my-database"
     - DATABASE_NAME="mydatabase"
     - DATABASE_PASS="mypassword"
     - DATABASE_PORT="5432"
     - DATABASE_USER="myuser"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

